on:
  push:
    branches: [develop]

name: Build and release

jobs:
  build:
    name: Generate the build
    if: ${{github.repository == 'devonfw/dashboard'}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies with NPM
        run: npm install
      - name: Build the distributable
        run: npm run dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          files: |
            ./dist/*.snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
