env:
    ORG: "devonfw"
    EMAIL: "icsddevonfwsupport.apps2@capgemini.com"
    REPO_SOURCE: "dashboard"
    REPO_DEST:  "dashboard.wiki"
    REPO_CONSOLIDATE: "devonfw-guide"
    GH_REPO_DEST: github.com/devonfw/dashboard.wiki.git
    GH_REPO_CONSOLIDATE: github.com/devonfw/devonfw-guide.git
on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop
name: Sync Wiki
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - name: Sync Wiki
            run: |
                cd ..
                git clone https://${GH_REPO_DEST}
                git clone https://${GH_REPO_CONSOLIDATE}
                cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
                cd ${REPO_DEST}
                grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
                if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
                    set +e 
                    pkill -9 -P $$ &> /dev/null || true 
                    exit 0
                else 
                    git config user.email ${EMAIL}
                    git config user.name ${USER}
                    git status
                    git add .
                    git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
                    git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
                    git push origin-wiki master
                    cd ../${REPO_CONSOLIDATE}
                    if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
                    git submodule init
                    git submodule update --recursive --remote
                    cd ${REPO_DEST}
                    git checkout master
                    git pull
                    cd ..
                    git add .
                    git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
                    git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
                    git push origin-wiki master
                fi
