env:
    REPO_SOURCE: "dashboard"
    REPO_DEST:  "dashboard.wiki"
on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop
name: Sync Wiki
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - name: Sync Wiki
            run: |
                yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
                cd ${REPO_DEST}
                grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
