on:
  push:

name: Run Tests

jobs:
  build:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run the tests with NPM
        run: npm run test
