env:
    REPO_CONSOLIDATE: "devonfw-guide"
on:
    push:
        branches:
            - develop
name: Sync Wiki
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - name: setup variables
            run: |
                echo "ORG=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
                echo "REPO_SOURCE=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
                echo "REPO_DEST=${REPO_SOURCE}.wiki" >> $GITHUB_ENV
            shell: bash
          - name: Generate build number
            uses: einaregilsson/build-number@v3
            with:
              token: ${{secrets.github_token}}
          - name: Checkout ${REPO_SOURCE} Repository
            uses: actions/checkout@v2
            with:
              path: ${REPO_SOURCE}
          - name: Checkout ${REPO_DEST} Repository
            run: git clone https://github.com/${ORG}/${REPO_DEST}.git ${REPO_DEST}
          - name: Checkout ${REPO_CONSOLIDATE} Repository
            uses: actions/checkout@v2
            with:
              path: ${REPO_CONSOLIDATE}
              repository: ${ORG}/${REPO_CONSOLIDATE}
          - name: Sync Wiki
            env:
                BUILD_USER: ${{ secrets.BUILD_USER }}
                BUILD_USER_PASSWD: ${{ secrets.BUILD_USER_PASSWD }}
                BUILD_USER_EMAIL:  ${{ secrets.BUILD_USER_EMAIL }}
            run: |
                cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
                cd ${REPO_DEST}
                grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
                if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
                    set +e 
                    pkill -9 -P $$ &> /dev/null || true 
                    exit 0
                else 
                    git config user.email ${BUILD_USER_EMAIL}
                    git config user.name ${BUILD_USER}
                    git status
                    git add .
                    git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
                    git remote add origin-wiki "https://${BUILD_USER}:${BUILD_USER_PASSWD}@github.com/${ORG}/${REPO_DEST}.git"
                    git push origin-wiki master
                    cd ../${REPO_CONSOLIDATE}
                    if [ ! -d ${REPO_DEST} ]; then git submodule add https://github.com/${ORG}/${REPO_DEST}.git; fi;
                    git submodule init
                    git submodule update --recursive --remote
                    cd ${REPO_DEST}
                    git checkout master
                    git pull
                    cd ..
                    git add .
                    git commit -m "${REPO_SOURCE} documentation | GitHub Actions build number $BUILD_NUMBER"
                    git remote add origin-wiki "https://${BUILD_USER}:${BUILD_USER_PASSWD}@github.com/${ORG}/${REPO_CONSOLIDATE}.git"
                    git push origin-wiki master
                fi
